added external api service OpenLibraryService
wolox-training/lm-java pull request #13
Opened 2019-08-13 19:59 UTC by mikolaslorant

## Summary

* added endpoint to get bookk by ISBN.
* added OpenLibraryService that uses external book api.
* added AuthorDTO, PublisherDTO and BookInfoDTO

## Trello card

https://trello.com/c/fP99JBMN/22-integraci%C3%B3n-api-externa

2019-08-13 20:44 UTC, IgnOliveto approved these changes

2019-08-14 17:41 UTC, IgnOliveto submitted a review, later dismissed

2019-08-17 00:50 UTC, leandrocostawolox requested changes
Good job! The only thing to comment: There are two fields which are not mapped from the open library API

2019-08-17 00:50 UTC, leandrocostawolox commented on training/src/main/java/wolox/training/models/Book.java
> +        this.image = "default_image";
The openlibrary API provides an image, but it's given with the name of "cover"

2019-08-17 00:50 UTC, leandrocostawolox commented on training/src/main/java/wolox/training/services/OpenLibraryService.java
> +        bookInfoDTO.setSubtitle(DEFAULT_SUBTITLE);
The openlibrary API provides a subtitle

2019-08-17 22:03 UTC, mikolaslorant commented on training/gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-5.4.1-all.zip
This was the configuration that was giving me a headache. Don't know why it wasn't set up like this in the first place.

2019-08-19 04:20 UTC, leandrocostawolox approved these changes

2019-08-19 04:23 UTC, IgnOliveto approved these changes

2019-08-20 01:54 UTC, merged