User controller
wolox-training/lm-java pull request #8
Opened 2019-07-19 16:25 UTC by mikolaslorant

## Summary

* added user controller with crud operations.
* add and romve book.

## Trello card

https://trello.com/c/gzElD0CS/21-crear-user-controller-con-las-operaciones-crud-de-user

2019-07-22 19:02 UTC, leandrocostawolox requested changes
Great job! I wrote some comments about this PR : )

2019-07-22 19:02 UTC, leandrocostawolox commented on training/src/main/java/wolox/training/controllers/UserController.java
> +    public User create(@RequestBody User user) {
It could be good to add @ResponseStatus(HttpStatus.CREATED)

2019-07-22 19:02 UTC, leandrocostawolox commented on training/src/main/java/wolox/training/controllers/UserController.java
> +    public User updateRemoveBook(@RequestBody Book book, @RequestParam int id) {
updateAddBook and updateRemoveBook shouldn't use Get mappings. The get operations are known as safe methods because they just retrieve information but don't change anything. Besides that, the GET methods usually don't use the body of the request.
In these cases, you can use PutMapping :)

2019-07-22 19:36 UTC, mikolaslorant commented on training/src/main/java/wolox/training/controllers/UserController.java
> +    public User updateRemoveBook(@RequestBody Book book, @RequestParam int id) {
Sorry for the oversight. Already fixed it ;)

2019-07-23 14:34 UTC, IgnOliveto approved these changes

2019-07-25 23:47 UTC, leandrocostawolox approved these changes
Great job!

2019-07-26 00:36 UTC, merged